### ISSUE TITLE
The /etc/modules-load.d/snap.qemu-virgil.conf file remains after purging snapd package

### ISSUE THREAD

**Issue by N0rbert** [ogra1/qemu-virgil-snap#10]
I'm actively testing the *quickemu* which uses *qemu-virgil* under the hood.

I need to share the finding - I have removed `snapd` package by `sudo apt purge snapd` , 
but the */etc/modules-load.d/snap.qemu-virgil.conf* file survived. I found this strange.

The host system is Ubuntu 20.04 LTS, the *qemu-virgil* is *--edge*.

**Comment by ogra1** [comment]
this is nothing the package itself handles or creates, looks like a bug in snapd, please file it at 

https://bugs.launchpad.net/snapd/+filebug

**Comment by N0rbert** [comment]
Done - https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1887134 . Thank you!
