### ISSUE TITLE
ubuntu 20.04 beta pulseaudio issue?

### ISSUE THREAD

**Issue by cmanville** [ogra1/qemu-virgil-snap#7]
I installed the qemu-virgil edge channel snap on ubuntu 20.04 beta and xubuntu 20.04 beta. When I try launching a virtual machine (I'm doing this with wimpy's quickemu) once the boot in the VM gets to a certain point the terminal gets spammed with:

```
pulseaudio: pa_threaded_mainloop_lock failed
pulseaudio: Reason: Access denied
```

ubuntu 20.04 beta guest still booted but had choppy audio. 
manjaro-xfce-19.0.2-minimal-200311-linux54 guest seemed to stop booting with a black screen.

I'm reporting this here since I don't have the knowledge to determine where the breakdown could be.

**Comment by bowes332frank** [comment]
You have to run qemu-virgil-snap under none-sudo environment.

**Comment by cmanville** [comment]
> You have to run qemu-virgil-snap under none-sudo environment.

Thank you for your reply, but I don't run qemu-virgil-snap with sudo. However your response made me look into this again because I since then upgraded hardware and reinstalled the OS. 
I was still experiencing the same problem, but ended up at least finding an answer for the terminal spam (the audio is still choppy, I assume that may be something else though). 
It turns out I wasn't the first to run into this [issue](https://github.com/wimpysworld/quickemu/issues/25) and that I just need to add `snap connect qemu-virgil:audio-record`.
