### ISSUE TITLE
could not open /dev/net/tun: Operation not permitted

### ISSUE THREAD

**Issue by carpiupin** [ogra1/qemu-virgil-snap#9]
I am running the follow command:

`qemu-virgil -enable-kvm -m 2048 -smp 2 -cpu host -device virtio-net,netdev=n0,mac=$MAC0 -netdev tap,id=n0,ifname=tap0,script=no,downscript=no -device virtio-vga,virgl=on -display sdl,gl=on -hda test_hda.img`

But got the following error:
`qemu-system-x86_64: could not open /dev/net/tun: Operation not permitted`

But it works fine if I use `qemu-system-x86_64 ` instead of `qemu-virgil`

How can I fix this problem? must I install this snap as root instead of sudo?

OS: Ubuntu 20.04

**Comment by ogra1** [comment]
can you try switching to the edge channel (there is a newer version in it with additional snap interfaces added as well ... note that the cmdline options might need some adjustments (qemu 4.x vs 3.x in stable):

    sudo snap refresh --edge qemu-virgil

that should switch you over, IIRC i added soemthing for tun/tap support there ...

**Comment by carpiupin** [comment]
This worked fine, thanks!!
